#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

ACTION="${1:-}"
VLM_CONDA_ENV="${VLM_CONDA_ENV:-/mnt/nas/share/home/hy/miniconda3/envs/rr-vlm-guidance-runtime}"
VLM_SERVER_ENV_FILE="${VLM_SERVER_ENV_FILE:-/mnt/nas/share/home/hy/vlm-guidance/server.env}"
VLM_RUNTIME_DIR="${VLM_RUNTIME_DIR:-/home/hy/.cache/rr-vlm-guidance}"
VLM_GPU_ID="${VLM_GPU_ID:-0}"
VLM_BIND_HOST="${VLM_BIND_HOST:-0.0.0.0}"
VLM_PORT="${VLM_PORT:-8000}"
VLM_MAX_START_USED_RATIO="${VLM_MAX_START_USED_RATIO:-0.10}"

PID_PATH="$VLM_RUNTIME_DIR/server.pid"
LOG_PATH="$VLM_RUNTIME_DIR/server.log"

usage() {
    cat <<'EOF'
Manage the HY Furniture VLM service in the shared NAS Conda environment.

Usage:
  conda_server.sh start
  conda_server.sh foreground
  conda_server.sh status
  conda_server.sh logs
  conda_server.sh stop
  conda_server.sh restart

Optional environment overrides:
  VLM_CONDA_ENV              Conda prefix containing Python and dependencies
  VLM_SERVER_ENV_FILE        Secret service environment file
  VLM_RUNTIME_DIR            Host-local PID/log directory
  VLM_GPU_ID                 Physical nvidia-smi GPU index (default: 0)
  VLM_BIND_HOST              Listen address (default: 0.0.0.0)
  VLM_PORT                   Listen port (default: 8000)
  VLM_MAX_START_USED_RATIO   Refuse startup at or above this ratio (default: 0.10)
EOF
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

process_is_live() {
    local pid="$1"
    local process_state
    [[ "$pid" =~ ^[0-9]+$ ]] || return 1
    kill -0 "$pid" 2>/dev/null || return 1
    process_state="$(ps -o stat= -p "$pid" 2>/dev/null | tr -d '[:space:]')"
    [[ -n "$process_state" && "${process_state:0:1}" != "Z" ]]
}

load_server_env() {
    [[ -f "$VLM_SERVER_ENV_FILE" ]] || {
        die "server env file not found: $VLM_SERVER_ENV_FILE"
    }
    # This file is generated by the deployment steps and is owned by the user.
    set -a
    # shellcheck disable=SC1090
    source "$VLM_SERVER_ENV_FILE"
    set +a
    local required
    for required in \
        VLM_CHECKPOINT_DIR \
        VLM_MANIFEST_PATH \
        VLM_API_TOKEN; do
        [[ -n "${!required:-}" ]] || die "$required is missing from $VLM_SERVER_ENV_FILE"
    done
}

validate_settings() {
    [[ "$VLM_GPU_ID" =~ ^[0-9]+$ ]] || die "VLM_GPU_ID must be a non-negative integer"
    [[ "$VLM_PORT" =~ ^[0-9]+$ ]] || die "VLM_PORT must be an integer"
    [[ -x "$VLM_CONDA_ENV/bin/python" ]] || {
        die "Python not found in Conda prefix: $VLM_CONDA_ENV"
    }
    "$VLM_CONDA_ENV/bin/python" - "$VLM_MAX_START_USED_RATIO" <<'PY'
import sys

ratio = float(sys.argv[1])
if not 0.0 <= ratio < 1.0:
    raise SystemExit("VLM_MAX_START_USED_RATIO must be in [0, 1)")
PY
}

assert_gpu_idle() {
    local gpu_row gpu_uuid total_mib used_mib existing_pids
    gpu_row="$(
        nvidia-smi \
            --query-gpu=index,uuid,memory.total,memory.used \
            --format=csv,noheader,nounits \
        | awk -F, -v wanted="$VLM_GPU_ID" '
            { gsub(/^[ \t]+|[ \t]+$/, "", $1) }
            $1 == wanted { print; found=1 }
            END { if (!found) exit 1 }
        '
    )" || die "GPU $VLM_GPU_ID was not returned by nvidia-smi"

    IFS=, read -r _ gpu_uuid total_mib used_mib <<< "$gpu_row"
    gpu_uuid="${gpu_uuid//[[:space:]]/}"
    total_mib="${total_mib//[[:space:]]/}"
    used_mib="${used_mib//[[:space:]]/}"

    existing_pids="$(
        nvidia-smi \
            --query-compute-apps=gpu_uuid,pid \
            --format=csv,noheader,nounits \
        | awk -F, -v wanted="$gpu_uuid" '
            {
                gsub(/^[ \t]+|[ \t]+$/, "", $1)
                gsub(/^[ \t]+|[ \t]+$/, "", $2)
            }
            $1 == wanted { print $2 }
        '
    )"
    if [[ -n "$existing_pids" ]]; then
        die "GPU $VLM_GPU_ID already has compute PID(s): ${existing_pids//$'\n'/,}"
    fi

    "$VLM_CONDA_ENV/bin/python" - \
        "$used_mib" "$total_mib" "$VLM_MAX_START_USED_RATIO" <<'PY'
import sys

used, total, maximum = map(float, sys.argv[1:])
ratio = used / total
if ratio >= maximum:
    raise SystemExit(
        f"GPU is not idle enough: {used:.0f}/{total:.0f} MiB "
        f"({ratio:.1%}) >= {maximum:.1%}"
    )
print(f"GPU preflight passed: {used:.0f}/{total:.0f} MiB ({ratio:.1%})")
PY
}

assert_port_available() {
    "$VLM_CONDA_ENV/bin/python" - "$VLM_BIND_HOST" "$VLM_PORT" <<'PY'
import socket
import sys

host, port = sys.argv[1], int(sys.argv[2])
with socket.socket() as server:
    server.bind((host, port))
PY
}

server_pid() {
    cat "$PID_PATH" 2>/dev/null || true
}

start_server() {
    validate_settings
    load_server_env
    mkdir -p "$VLM_RUNTIME_DIR"
    chmod 700 "$VLM_RUNTIME_DIR"

    local pid
    pid="$(server_pid)"
    if process_is_live "$pid"; then
        die "VLM service is already running as PID $pid"
    fi
    assert_gpu_idle
    assert_port_available

    nohup env \
        CUDA_VISIBLE_DEVICES="$VLM_GPU_ID" \
        PYTHONNOUSERSITE=1 \
        PYTHONPATH="$REPO_ROOT" \
        "$VLM_CONDA_ENV/bin/python" -m uvicorn \
        services.vlm_guidance.app:app \
        --host "$VLM_BIND_HOST" \
        --port "$VLM_PORT" \
        --workers 1 \
        > "$LOG_PATH" 2>&1 < /dev/null &
    pid=$!
    printf '%s\n' "$pid" > "$PID_PATH"
    sleep 2
    if ! process_is_live "$pid"; then
        tail -n 100 "$LOG_PATH" >&2 || true
        die "VLM service exited during startup"
    fi
    echo "VLM service starting as PID $pid; log: $LOG_PATH"
    echo "Run '$0 status' until readiness reports status=ready."
}

stop_server() {
    local pid cmdline
    pid="$(server_pid)"
    if ! process_is_live "$pid"; then
        echo "VLM service is not running"
        return 0
    fi
    cmdline="$(tr '\0' ' ' < "/proc/$pid/cmdline" 2>/dev/null || true)"
    case "$cmdline" in
        *"-m uvicorn services.vlm_guidance.app:app"*) ;;
        *) die "refusing to signal PID $pid; command does not match the VLM service" ;;
    esac
    kill -TERM "$pid"
    for _ in $(seq 1 150); do
        if ! process_is_live "$pid"; then
            echo "VLM service stopped"
            return 0
        fi
        sleep 0.2
    done
    die "service did not exit after SIGTERM; no SIGKILL was sent"
}

show_status() {
    validate_settings
    load_server_env
    local pid
    pid="$(server_pid)"
    if process_is_live "$pid"; then
        echo "process_alive=true pid=$pid"
    else
        echo "process_alive=false"
    fi
    nvidia-smi -i "$VLM_GPU_ID" \
        --query-gpu=index,uuid,memory.total,memory.used,utilization.gpu \
        --format=csv,noheader
    curl --fail --show-error --silent --max-time 5 \
        -H "Authorization: Bearer $VLM_API_TOKEN" \
        "http://127.0.0.1:$VLM_PORT/health/ready"
    echo
}

foreground_server() {
    validate_settings
    load_server_env
    assert_gpu_idle
    assert_port_available
    export CUDA_VISIBLE_DEVICES="$VLM_GPU_ID"
    export PYTHONNOUSERSITE=1
    export PYTHONPATH="$REPO_ROOT"
    exec "$VLM_CONDA_ENV/bin/python" -m uvicorn \
        services.vlm_guidance.app:app \
        --host "$VLM_BIND_HOST" \
        --port "$VLM_PORT" \
        --workers 1
}

case "$ACTION" in
    start)
        start_server
        ;;
    foreground)
        foreground_server
        ;;
    status)
        show_status
        ;;
    logs)
        tail -n 200 "$LOG_PATH"
        ;;
    stop)
        stop_server
        ;;
    restart)
        stop_server
        start_server
        ;;
    -h|--help|help|"")
        usage
        ;;
    *)
        usage >&2
        die "unknown action: $ACTION"
        ;;
esac
